### PR TITLE
Ultimate merger of dev-0.5 branch.

### PR DESCRIPTION
**Pull request by cerebrate**

### CODE REVIEW

**Comment by mangkoran** [comment]
@cerebrate I would like to contribute for the Readme. However, I think it is too small for a separate PR. May I send a patch to you?

**Comment by cerebrate** [comment]
Sure, go ahead.

**Comment by mangkoran** [comment]
[Here](https://gist.github.com/mangkoran/bd1e127affb6e579ff4a19c1413e186f) is the patch. You might want to review and change it to suit your style. Thank you!

**Comment by cerebrate** [comment]
Thanks for the proofread. I've committed it and a few revisions of my own now.

**Pull request merged**
